// DefaultCommon.hlsl
// ENGINE: Common structures, texture declarations, and basic utility functions
// Part of Default visual style shader architecture

#ifndef DEFAULT_COMMON_INCLUDED
#define DEFAULT_COMMON_INCLUDED

// SRP Batcher compatibility - Material properties
CBUFFER_START(UnityPerMaterial)
    float4 _ProvinceIDTexture_ST;
    float4 _ProvinceOwnerTexture_ST;
    float4 _ProvinceColorTexture_ST;
    float4 _ProvinceDevelopmentTexture_ST;
    float4 _ProvinceTerrainTexture_ST;
    float4 _HeightmapTexture_ST;
    float4 _NormalMapTexture_ST;
    float4 _ProvinceColorPalette_ST;
    float4 _CountryColorPalette_ST;
    float4 _DistanceFieldBorderTexture_ST;
    float4 _PixelPerfectBorderTexture_ST;
    float4 _HighlightTexture_ST;
    float4 _MainTex_ST;

    int _MapMode;
    int _CustomMapModeIndex;  // Index into _ProvincePaletteTexture rows for GAME-defined map modes
    int _MapModeTextureCount; // Number of registered map mode palettes
    int _MaxProvinceID;       // Maximum province ID for palette bounds checking

    // Tessellation parameters
    float _HeightScale;
    float _TessellationFactor;
    float _TessellationMaxDistance;
    float _TessellationMinDistance;

    // Border parameters (configurable from VisualStyleConfiguration)
    // Mode values: 0=None, 1=ShaderDistanceField, 2=ShaderPixelPerfect, 3=MeshGeometry
    int _BorderRenderingMode;
    float _CountryBorderStrength;
    float4 _CountryBorderColor;
    float _ProvinceBorderStrength;
    float4 _ProvinceBorderColor;

    // Vector curve border parameters
    float _UseVectorCurves;
    uint _BezierSegmentCount;
    int _MapWidth;
    int _MapHeight;

    // Spatial grid parameters
    int _GridWidth;
    int _GridHeight;
    int _GridCellSize;

    // Map mode colors (configurable from VisualStyleConfiguration)
    float4 _OceanColor;
    float4 _UnownedLandColor;

    // Development gradient colors (configurable from VisualStyleConfiguration)
    float4 _DevVeryLow;
    float4 _DevLow;
    float4 _DevMedium;
    float4 _DevHigh;
    float4 _DevVeryHigh;

    // Development tier thresholds
    float _DevTier1;
    float _DevTier2;
    float _DevTier3;
    float _DevTier4;

    // Terrain adjustments
    float _TerrainBrightness;
    float _TerrainSaturation;

    // Terrain detail mapping
    float _DetailTiling;
    float _DetailStrength;
    float _TriPlanarTightenFactor;

    // Normal mapping lighting controls
    float _NormalMapStrength;
    float _NormalMapAmbient;
    float _NormalMapHighlight;

    float _HighlightStrength;

    // Advanced Effects parameters
    float4 _OverlayTexture_ST;
    float _OverlayStrength;
    float _CountryColorSaturation;

    // Fog of War parameters
    float _FogOfWarEnabled;
    float _FogOfWarZoomDisable;
    float4 _FogUnexploredColor;
    float4 _FogExploredColor;
    float _FogExploredDesaturation;
    float _FogNoiseScale;
    float _FogNoiseStrength;
    float _FogNoiseSpeed;
    float4 _FogNoiseColor;

    // AAA Distance Field Border Parameters
    float _EdgeWidth;
    float _GradientWidth;
    float _EdgeSmoothness;
    float _EdgeColorMul;
    float _GradientColorMul;
    float _EdgeAlpha;
    float _GradientAlphaInside;
    float _GradientAlphaOutside;
CBUFFER_END

// Texture declarations - Core simulation textures
TEXTURE2D(_ProvinceIDTexture); SAMPLER(sampler_ProvinceIDTexture);
TEXTURE2D(_ProvinceOwnerTexture); SAMPLER(sampler_ProvinceOwnerTexture);
TEXTURE2D(_ProvinceColorTexture); SAMPLER(sampler_ProvinceColorTexture);
TEXTURE2D(_ProvinceDevelopmentTexture); SAMPLER(sampler_ProvinceDevelopmentTexture);
TEXTURE2D(_ProvinceTerrainTexture); SAMPLER(sampler_ProvinceTerrainTexture);
TEXTURE2D(_TerrainTypeTexture); SAMPLER(sampler_TerrainTypeTexture);
// Province terrain lookup buffer (same pattern as ProvinceOwnerBuffer in PopulateOwnerTexture.compute)
// Indexed by province ID: ProvinceTerrainBuffer[provinceID] = terrainTypeIndex (0-255)
StructuredBuffer<uint> _ProvinceTerrainBuffer;
TEXTURE2D_ARRAY(_TerrainDetailArray); SAMPLER(sampler_TerrainDetailArray);
TEXTURE2D(_DetailNoiseTexture); SAMPLER(sampler_DetailNoiseTexture);
TEXTURE2D(_HeightmapTexture); SAMPLER(sampler_HeightmapTexture);
TEXTURE2D(_NormalMapTexture); SAMPLER(sampler_NormalMapTexture);

// Imperator Rome-style terrain blend maps (generated by TerrainBlendMapGenerator)
TEXTURE2D(_DetailIndexTexture); SAMPLER(sampler_DetailIndexTexture);  // RGBA8: 4 material indices per pixel
TEXTURE2D(_DetailMaskTexture); SAMPLER(sampler_DetailMaskTexture);    // RGBA8: 4 blend weights per pixel
TEXTURE2D(_ProvinceColorPalette); SAMPLER(sampler_ProvinceColorPalette);
TEXTURE2D(_CountryColorPalette); SAMPLER(sampler_CountryColorPalette);
TEXTURE2D(_TerrainColorPalette); SAMPLER(sampler_TerrainColorPalette);
// Border textures - each mode has its own dedicated texture
TEXTURE2D(_DistanceFieldBorderTexture); SAMPLER(sampler_DistanceFieldBorderTexture);  // Mode 1: JFA distance field (R=country, G=province)
TEXTURE2D(_PixelPerfectBorderTexture); SAMPLER(sampler_PixelPerfectBorderTexture);    // Mode 2: Sharp 1px borders (R=country, G=province)
TEXTURE2D(_HighlightTexture); SAMPLER(sampler_HighlightTexture);
TEXTURE2D(_FogOfWarTexture); SAMPLER(sampler_FogOfWarTexture);
TEXTURE2D(_OverlayTexture); SAMPLER(sampler_OverlayTexture);
TEXTURE2D(_MainTex); SAMPLER(sampler_MainTex); // For SRP Batcher

// Province Palette Texture - ENGINE mechanism for GAME-defined map modes
// Layout: 256 columns x (maxProvinces/256 * numModes) rows
// Each map mode gets (maxProvinces/256) rows, stacked vertically
// ProvinceID -> x = ID % 256, y = (ID / 256) + (modeIndex * rowsPerMode)
// Switching map modes = changing _CustomMapModeIndex (row offset), instant GPU-side
// Memory: 100k provinces * 16 modes * 4 bytes = ~6.4MB (vs 6.24GB for full-res array)
TEXTURE2D(_ProvincePaletteTexture); SAMPLER(sampler_ProvincePaletteTexture);

// CRITICAL: Include BezierCurves.hlsl to define BezierSegment struct
#include "../BezierCurves.hlsl"

// Vector curve border buffers (set from C#)
StructuredBuffer<BezierSegment> _BezierSegments;
StructuredBuffer<uint2> _GridCellRanges;         // Per-cell (startIndex, count)
StructuredBuffer<uint> _GridSegmentIndices;       // Flat segment indices

#endif // DEFAULT_COMMON_INCLUDED
